* My Lunch and learn
** TODO create outline

   create outline describing the three main front-end technologies.
   Their responsibilities and best practices. Should describe why
   that technology is responsible for that section. Should also
   discuss the implications of having that responsibility, Best
   practices should also have explanations as to why they are what
   they are.

** HTML

*** history

    - 1989 An Idea :: Tim Berners-Lee has an idea to help researchers
      collaborate no matter where they were on the planet. Not by just
      pooling there files together, but have the ability to link
      documents together by some form of 'hypertext'.
    - 1990 HTML Specification :: Tim Berners-Lee writes the
      specification, the browser and server software.
    - 1991 HTML 1 :: First public mention of HTML which originally
      consisted of 18 tags defined [[http://info.cern.ch/hypertext/WWW/MarkUp/Tags.html][here]]
    - HTML 2.0 :: released in 1995
    - HTML 5 :: released in 2014

*** responsibility

**** why

*** best practices

** CSS

*** history

*** responsibility

**** why

*** best practices

** Java-script

*** history

*** responsibility

**** why

*** best practices
